### ISSUE TITLE
Implement different UIStates for HUD and potentially add a set of substates for each HUD state.

### ISSUE THREAD

**Issue by camwalford** [COMP2522/project-scuffed-civ#73]
- a state for when it is the player's turn
- a state for when it's the enemies turn
- a state for when the game is over (player has won or lost)
- a state for a pause menu maybe?
- substates when entities are selected that show actions that they can perform, etc. Whatever feels necessary.

***This isn't the only way to do it, it's just consistent with how the menu has been done so far.***

**Comment by Brendan-Doy1e** [comment]
Made an in game hud state and in game menu state. load info on unit selection.
