### ISSUE TITLE
Fix the size of the "End turn" button, so it is not cut off the screen, as well consider not letting the user not being able to click end turn while on the menu

### ISSUE THREAD

**Issue by victoramaim** [COMP2522/project-scuffed-civ#89]
https://github.com/COMP2522/project-scuffed-civ/blob/9c28a095444a331ef13dfca77705ae6530b5d995/src/main/java/org/bcit/com2522/project/scuffed/client/menuHUDState.java#L37

**Comment by Brendan-Doy1e** [comment]
fixed
